spring.application.name=workshopmongo
spring.mongodb.uri=mongodb+srv://root:${MONGO_PASSWORD}@cluster-aula2.jysnziw.mongodb.net/workshop_mongo?appName=Cluster-aula2
server.error.include-message=always
server.error.include-binding-errors=always